/**
 * What ties the kit to your Notion database and to your site.
 *
 * Property names are matched exactly, including case and spaces: rename a property in Notion,
 * rename it here. Nothing else in the kit refers to property names.
 */

/** How a row counts as published: a ticked checkbox, or a status/select set to a given option. */
export type PublishRule =
  | { type: 'checkbox'; property: string }
  | { type: 'status' | 'select'; property: string; equals: string };

export type PropertyNames = {
  /** Title property, rendered as the post's h1. */
  title: string;
  /** Rich text property with the URL segment, e.g. "my-first-post". Required. */
  slug: string;
  /** Date shown on the post and used to sort. Falls back to the page's creation time. */
  date: string;
  /** Optional "last updated" date, used for dateModified and the sitemap. */
  updated: string;
  excerpt: string;
  /** Optional <title> override. */
  seoTitle: string;
  /** Optional meta description override (falls back to the excerpt). */
  metaDescription: string;
  /** Optional canonical URL, for posts first published elsewhere. */
  canonicalUrl: string;
  category: string;
  tags: string;
  /** Author as text, a select or a Notion person. */
  author: string;
  /** Cover as a URL or files property. Falls back to the page cover. */
  cover: string;
  /** Plain description of the cover for screen readers and search. Empty means decorative. */
  coverAlt: string;
  /** Checkbox: the cover was generated by AI, so its alt text says so. */
  aiImage: string;
};

export type BlogConfig = {
  /** Notion data source id, database id, or the database's full URL. */
  dataSource: string;
  publish: PublishRule;
  properties: PropertyNames;
  /** Where posts live on the site, e.g. "/blog". */
  basePath: string;
  /** Canonical origin of the site, e.g. "https://www.example.com". */
  siteUrl: string;
  siteName: string;
  /** One sentence about the site, for meta tags, the RSS feed and llms.txt. */
  description: string;
  /** Route that serves images uploaded to Notion, e.g. "/notion-image". */
  imagePath: string;
};

export const DEFAULT_PROPERTIES: PropertyNames = {
  title: 'Name',
  slug: 'Slug',
  date: 'Published date',
  updated: 'Last updated',
  excerpt: 'Excerpt',
  seoTitle: 'SEO title',
  metaDescription: 'Meta description',
  canonicalUrl: 'Canonical URL',
  category: 'Category',
  tags: 'Tags',
  author: 'Author',
  cover: 'Cover',
  coverAlt: 'Cover alt',
  aiImage: 'AI image',
};

export type BlogConfigInput = Partial<Omit<BlogConfig, 'properties'>> & { properties?: Partial<PropertyNames> };

const path = (value: string) => `/${value.replace(/^\/+|\/+$/g, '')}`.replace(/^\/$/, '');

export function defineBlogConfig(input: BlogConfigInput = {}): BlogConfig {
  return {
    dataSource: input.dataSource ?? '',
    publish: input.publish ?? { type: 'checkbox', property: 'Published' },
    properties: { ...DEFAULT_PROPERTIES, ...input.properties },
    basePath: path(input.basePath ?? '/blog'),
    siteUrl: (input.siteUrl ?? 'http://localhost:3000').replace(/\/+$/, ''),
    siteName: input.siteName ?? 'Blog',
    description: input.description ?? '',
    imagePath: path(input.imagePath ?? '/notion-image'),
  };
}
