/**
 * What ties the kit to your Notion database and to your site.
 *
 * Property names are matched exactly, including case and spaces: rename a property in Notion,
 * rename it here. Nothing else in the kit refers to property names.
 */

/** How a row counts as published: a ticked checkbox, or a status/select set to a given option. */
export type PublishRule =
  | { type: 'checkbox'; property: string }
  | { type: 'status' | 'select'; property: string; equals: string };

export type PropertyNames = {
  /** Title property, rendered as the post's h1. */
  title: string;
  /** Rich text property with the URL segment, e.g. "my-first-post". Required. */
  slug: string;
  /** Date shown on the post and used to sort. Falls back to the page's creation time. */
  date: string;
  /** Optional "last updated" date, used for dateModified and the sitemap. */
  updated: string;
  excerpt: string;
  /** Optional <title> override. */
  seoTitle: string;
  /** Optional meta description override (falls back to the excerpt). */
  metaDescription: string;
  /** Optional canonical URL, for posts first published elsewhere. */
  canonicalUrl: string;
  category: string;
  tags: string;
  /** Author as text, a select or a Notion person. */
  author: string;
  /**
   * Cover as a URL or files property, or several names tried in order (for databases where old
   * and new posts keep their cover in different properties). Falls back to the page cover.
   */
  cover: string | string[];
  /** Plain description of the cover for screen readers and search. Empty means decorative. */
  coverAlt: string;
  /** Checkbox: the cover was generated by AI, so its alt text says so. */
  aiImage: string;
  /** Checkbox: featured rows are listed first. Empty (the default) keeps the plain newest-first order. */
  featured: string;
};

export type BlogConfig = {
  /** Notion data source id, database id, or the database's full URL. */
  dataSource: string;
  publish: PublishRule;
  properties: PropertyNames;
  /** Where posts live on the site, e.g. "/blog". */
  basePath: string;
  /** Canonical origin of the site, e.g. "https://www.example.com". */
  siteUrl: string;
  siteName: string;
  /** One sentence about the site, for meta tags, the RSS feed and llms.txt. */
  description: string;
  /** Name of the collection in breadcrumbs and llms.txt, e.g. "Blog" or "Customer stories". */
  label: string;
  /** schema.org type of each entry: BlogPosting for a blog, Article for case studies and guides. */
  articleType: 'BlogPosting' | 'Article';
  /** Route that serves images uploaded to Notion, e.g. "/notion-image". */
  imagePath: string;
  /**
   * Extra properties to read as text, by key: `{ product: 'Product' }` gives `post.extra.product`.
   * For site-specific data the kit does not know about.
   */
  extra: Record<string, string>;
  /**
   * Extra image properties, by key: `{ avatar: 'Avatar' }` gives `post.images.avatar`, served like
   * the cover. A list of names is tried in order. There is no fallback to the page cover.
   */
  images: Record<string, string | string[]>;
};

export const DEFAULT_PROPERTIES: PropertyNames = {
  title: 'Name',
  slug: 'Slug',
  date: 'Published date',
  updated: 'Last updated',
  excerpt: 'Excerpt',
  seoTitle: 'SEO title',
  metaDescription: 'Meta description',
  canonicalUrl: 'Canonical URL',
  category: 'Category',
  tags: 'Tags',
  author: 'Author',
  cover: 'Cover',
  coverAlt: 'Cover alt',
  aiImage: 'AI image',
  featured: '',
};

export type BlogConfigInput = Partial<Omit<BlogConfig, 'properties'>> & { properties?: Partial<PropertyNames> };

const path = (value: string) => `/${value.replace(/^\/+|\/+$/g, '')}`.replace(/^\/$/, '');

export function defineBlogConfig(input: BlogConfigInput = {}): BlogConfig {
  return {
    dataSource: input.dataSource ?? '',
    publish: input.publish ?? { type: 'checkbox', property: 'Published' },
    properties: { ...DEFAULT_PROPERTIES, ...input.properties },
    basePath: path(input.basePath ?? '/blog'),
    siteUrl: (input.siteUrl ?? 'http://localhost:3000').replace(/\/+$/, ''),
    siteName: input.siteName ?? 'Blog',
    description: input.description ?? '',
    label: input.label ?? 'Blog',
    articleType: input.articleType ?? 'BlogPosting',
    imagePath: path(input.imagePath ?? '/notion-image'),
    extra: { ...input.extra },
    images: { ...input.images },
  };
}

/** Property names of a changelog database: one row per release. */
export type ChangelogPropertyNames = {
  /** Title property: the release's name, e.g. "Faster exports". */
  title: string;
  /** Version, e.g. "2.3.0". Gives the release its anchor when set. */
  version: string;
  /** Release date. Falls back to the page's creation time. */
  date: string;
  /** Optional product or area, shown as a label (text or select). */
  product: string;
  /** Optional one-line summary, for the feed and llms.txt. */
  summary: string;
};

/** A text property with one change per line, rendered as a list under its label. */
export type ChangelogSection = { label: string; property: string };

export type ChangelogConfig = {
  /** Notion data source id, database id, or the database's full URL. Empty turns the changelog off. */
  dataSource: string;
  publish: PublishRule;
  properties: ChangelogPropertyNames;
  /** The list properties, in the order they are shown. */
  sections: ChangelogSection[];
  /** Also render each release's page content. One Notion call per release, cached like a post. */
  body: boolean;
  /** Where the changelog lives on the site, e.g. "/changelog". */
  basePath: string;
  /** Name in navigation, breadcrumbs and llms.txt. */
  label: string;
  siteUrl: string;
  siteName: string;
  description: string;
  imagePath: string;
};

export const DEFAULT_CHANGELOG_PROPERTIES: ChangelogPropertyNames = {
  title: 'Name',
  version: 'Version',
  date: 'Release date',
  product: 'Product',
  summary: 'Summary',
};

export const DEFAULT_CHANGELOG_SECTIONS: ChangelogSection[] = [
  { label: 'New', property: 'New' },
  { label: 'Improved', property: 'Improved' },
  { label: 'Fixed', property: 'Fixed' },
];

export type ChangelogConfigInput = Partial<Omit<ChangelogConfig, 'properties'>> & { properties?: Partial<ChangelogPropertyNames> };

export function defineChangelogConfig(input: ChangelogConfigInput = {}): ChangelogConfig {
  return {
    dataSource: input.dataSource ?? '',
    publish: input.publish ?? { type: 'checkbox', property: 'Published' },
    properties: { ...DEFAULT_CHANGELOG_PROPERTIES, ...input.properties },
    sections: (input.sections ?? DEFAULT_CHANGELOG_SECTIONS).map((section) => ({ ...section })),
    body: input.body ?? true,
    basePath: path(input.basePath ?? '/changelog'),
    label: input.label ?? 'Changelog',
    siteUrl: (input.siteUrl ?? 'http://localhost:3000').replace(/\/+$/, ''),
    siteName: input.siteName ?? 'Blog',
    description: input.description ?? '',
    imagePath: path(input.imagePath ?? '/notion-image'),
  };
}
